/*
 * This source file was generated by the Gradle 'init' task
 */
package mcrandomize;

import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.entity.Player;
import org.bukkit.event.Listener;
import org.bukkit.event.EventHandler;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.event.entity.EntityDamageEvent;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import java.util.Random;
import java.util.Arrays;
import java.util.List;

public class McRandomizePlugin extends JavaPlugin implements Listener {
    private final Random random = new Random();
    private final List<Material> possibleItems = Arrays.asList(
        Material.DIAMOND, Material.IRON_INGOT, Material.GOLD_INGOT,
        Material.EMERALD, Material.COAL, Material.REDSTONE,
        Material.LAPIS_LAZULI, Material.QUARTZ, Material.GLOWSTONE_DUST
    );
    private final List<PotionEffectType> possibleEffects = Arrays.asList(
        PotionEffectType.SPEED, PotionEffectType.JUMP,
        PotionEffectType.INVISIBILITY, PotionEffectType.GLOWING,
        PotionEffectType.LEVITATION, PotionEffectType.SLOW_FALLING,
        PotionEffectType.CONFUSION, PotionEffectType.BLINDNESS
    );

    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(this, this);
        getLogger().info("McRandomize has been enabled!");
    }

    @Override
    public void onDisable() {
        getLogger().info("McRandomize has been disabled!");
    }

    @EventHandler
    public void onBlockBreak(BlockBreakEvent event) {
        Player player = event.getPlayer();
        
        // Random chance to give a random item
        if (random.nextFloat() < 0.3) { // 30% chance
            Material randomItem = possibleItems.get(random.nextInt(possibleItems.size()));
            player.getInventory().addItem(new ItemStack(randomItem, 1));
            player.sendMessage("§aYou found a random item: " + randomItem.name());
        }
    }

    @EventHandler
    public void onEntityDamage(EntityDamageEvent event) {
        if (event.getEntity() instanceof Player) {
            Player player = (Player) event.getEntity();
            
            // Randomize damage
            double randomDamage = random.nextDouble() * 10.0; // Random damage between 0 and 10
            event.setDamage(randomDamage);
            
            // Random chance to apply a random effect
            if (random.nextFloat() < 0.4) { // 40% chance
                PotionEffectType randomEffect = possibleEffects.get(random.nextInt(possibleEffects.size()));
                int duration = random.nextInt(600) + 200; // Random duration between 10 and 30 seconds
                int amplifier = random.nextInt(2); // Random amplifier between 0 and 1
                
                player.addPotionEffect(new PotionEffect(randomEffect, duration * 20, amplifier));
                player.sendMessage("§dYou got a random effect: " + randomEffect.getName());
            }
        }
    }
}
